name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # Change this to match your .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet publish -c Release -o publish_output

      - name: Install AWS CLI
        run: |
          sudo apt update
          sudo apt install -y unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: Install Elastic Beanstalk CLI
        run: |
          pip install awsebcli --upgrade --user
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          eb --version

      - name: Zip the application
        run: zip -r deploy-package.zip publish_output/

      - name: Deploy to AWS Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1" # Change to your AWS region
          EB_ENV_NAME: "your-eb-environment-name" # Change this to your Elastic Beanstalk environment name
          EB_APP_NAME: "your-eb-application-name" # Change this to your Elastic Beanstalk application name
        run: |
          eb init $EB_APP_NAME --region $AWS_REGION --platform "dotnet"
          eb use $EB_ENV_NAME
          eb deploy
